import Publications from "./publications";

const outputs = [
  { year: 2025, type: "Journal article", title: "Housing and husbandry factors affecting zebrafish novel tank test responses: a global multi-laboratory study", authors: "Hillman C, Fontana BD, … Gallas-Lopes M, et al.", venue: "Lab Animal", url: "https://scholar.google.com/scholar?q=Housing+and+husbandry+factors+affecting+zebrafish+novel+tank+test+responses" },
  { year: 2025, type: "Journal article", title: "Neurological effects induced by micro- and nanoplastics in fish: a systematic review and meta-analysis", authors: "Zanona QK, Gallas-Lopes M, et al.", venue: "Journal of Hazardous Materials", url: "https://scholar.google.com/scholar?q=Neurological+effects+induced+by+micro+and+nanoplastics+in+fish" },
  { year: 2025, type: "Preprint", title: "Estimating the replicability of Brazilian biomedical science", authors: "The Brazilian Reproducibility Initiative, Gallas-Lopes M, et al.", venue: "bioRxiv", url: "https://scholar.google.com/scholar?q=Estimating+the+replicability+of+Brazilian+biomedical+science" },
  { year: 2025, type: "Preprint", title: "Ketamine-induced NMDA receptor hypofunction alters social behavior in adult zebrafish", authors: "Gallas-Lopes M, Muller DV, Stahlhofer-Buss T, et al.", venue: "bioRxiv", url: "https://scholar.google.com/scholar?q=Ketamine-induced+NMDA+receptor+hypofunction+alters+social+behavior+in+adult+zebrafish" },
  { year: 2024, type: "Journal article", title: "Behavioral and neurochemical effects of carbofuran in zebrafish", authors: "Oliveira GR, Gallas-Lopes M, et al.", venue: "Comparative Biochemistry and Physiology C", url: "https://scholar.google.com/scholar?q=Behavioral+and+neurochemical+effects+of+carbofuran+in+zebrafish" },
  { year: 2023, type: "Journal article", title: "Effects of taurine in mice and zebrafish behavioral assays with translational relevance to schizophrenia", authors: "Giongo FK, Gallas-Lopes M, Benvenutti R, et al.", venue: "International Journal of Neuropsychopharmacology", url: "https://doi.org/10.1093/ijnp/pyad018" },
  { year: 2023, type: "Journal article", title: "Systematic review and meta-analysis of 10 years of unpredictable chronic stress in zebrafish", authors: "Gallas-Lopes M, Bastos LM, Benvenutti R, et al.", venue: "Lab Animal", url: "https://scholar.google.com/scholar?q=Systematic+review+and+meta-analysis+of+10+years+of+unpredictable+chronic+stress+in+zebrafish" },
  { year: 2023, type: "Journal article", title: "A systematic review of the impact of environmental enrichment in zebrafish", authors: "Gallas-Lopes M, Benvenutti R, Donzelli NIZ, et al.", venue: "Lab Animal", url: "https://scholar.google.com/scholar?q=A+systematic+review+of+the+impact+of+environmental+enrichment+in+zebrafish" },
  { year: 2023, type: "Journal article", title: "Chemically-induced epileptic seizures in zebrafish: a systematic review", authors: "Chitolina R, Gallas-Lopes M, et al.", venue: "Epilepsy Research", url: "https://scholar.google.com/scholar?q=Chemically-induced+epileptic+seizures+in+zebrafish+a+systematic+review" },
  { year: 2023, type: "Journal article", title: "Neurobehavioral effects of fungicides in zebrafish: a systematic review and meta-analysis", authors: "Reis CG, Bastos LM, Chitolina R, Gallas-Lopes M, et al.", venue: "Scientific Reports", url: "https://scholar.google.com/scholar?q=Neurobehavioral+effects+of+fungicides+in+zebrafish" },
  { year: 2022, type: "Journal article", title: "Curcumin micronization by supercritical fluid: in vitro and in vivo biological relevance", authors: "Sachett A, Gallas-Lopes M, Benvenutti R, et al.", venue: "Industrial Crops and Products", url: "https://scholar.google.com/scholar?q=Curcumin+micronization+by+supercritical+fluid" },
  { year: 2022, type: "Journal article", title: "Micronized curcumin causes hyperlocomotion in zebrafish larvae", authors: "Sachett A, Benvenutti R, Reis CG, Gallas-Lopes M, et al.", venue: "Neurochemical Research", url: "https://scholar.google.com/scholar?q=Micronized+curcumin+causes+hyperlocomotion+in+zebrafish+larvae" },
  { year: 2022, type: "Journal article", title: "What do male and female zebrafish prefer? Directional and colour preference in maze tasks", authors: "Marcon M, Benvenutti R, Gallas-Lopes M, et al.", venue: "European Journal of Neuroscience", url: "https://scholar.google.com/scholar?q=What+do+male+and+female+zebrafish+prefer" },
  { year: 2022, type: "Review", title: "Glutamate NMDA receptor antagonists with relevance to schizophrenia: a review of zebrafish behavioral studies", authors: "Piato A, Benvenutti R, Gallas-Lopes M, et al.", venue: "Current Neuropharmacology", url: "https://scholar.google.com/scholar?q=Glutamate+NMDA+receptor+antagonists+with+relevance+to+schizophrenia" },
  { year: 2021, type: "Journal article", title: "How do zebrafish respond to MK-801 and amphetamine?", authors: "Benvenutti R, Gallas-Lopes M, et al.", venue: "Journal of Neuroscience Research", url: "https://scholar.google.com/scholar?q=How+do+zebrafish+respond+to+MK-801+and+amphetamine" },
  { year: 2021, type: "Review", title: "Swimming in the maze: an overview of maze apparatuses and protocols to assess zebrafish behavior", authors: "Benvenutti R, Marcon M, Gallas-Lopes M, et al.", venue: "Neuroscience & Biobehavioral Reviews", url: "https://scholar.google.com/scholar?q=Swimming+in+the+maze+zebrafish" },
  { year: 2020, type: "Review", title: "Corticotropin-releasing factor receptor signaling and modulation", authors: "Vasconcelos M, Stein DJ, Gallas-Lopes M, et al.", venue: "Trends in Psychiatry and Psychotherapy", url: "https://scholar.google.com/scholar?q=Corticotropin-releasing+factor+receptor+signaling+and+modulation" },
];

type SiteOutput=(typeof outputs)[number]&{date?:string;id?:string};
const labels:Record<string,string>={article:"Journal article",review:"Review",preprint:"Preprint","conference-paper":"Conference paper","conference-abstract":"Conference abstract",dataset:"Dataset",software:"Software"};
async function getLiveOutputs():Promise<SiteOutput[]>{
  const key=process.env.OPENALEX_API_KEY;
  if(!key)return [];
  const fields="id,title,publication_date,publication_year,type,authorships,primary_location,locations,doi,cited_by_count,ids";
  const base=`https://api.openalex.org/works?filter=author.id:A5058545919&per_page=200&select=${fields}&api_key=${encodeURIComponent(key)}`;
  const records:any[]=[];let cursor="*";
  for(let page=0;page<10;page++){
    const response=await fetch(`${base}&cursor=${encodeURIComponent(cursor)}`,{next:{revalidate:86400}});
    if(!response.ok)return [];
    const data=await response.json();records.push(...(data.results||[]));
    if(!data.meta?.next_cursor)break;cursor=data.meta.next_cursor;
  }
  const seen=new Set<string>();
  return records.map((work:any)=>{
    const doi=(work.doi||"").toLowerCase();const source=work.primary_location?.source?.display_name||"";
    const protocol=doi.includes("10.17504/protocols.io");const type=protocol?"Protocol":(labels[work.type]||"Other output");
    const authors=(work.authorships||[]).map((a:any)=>a.author?.display_name).filter(Boolean).join(", ");
    return {id:work.id,date:work.publication_date,year:work.publication_year,type,title:work.title,authors,venue:source,url:work.doi||work.primary_location?.landing_page_url||work.id};
  }).filter((item:SiteOutput)=>{const key=(item.url||item.id||item.title).toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).sort((a:SiteOutput,b:SiteOutput)=>(b.date||`${b.year}`).localeCompare(a.date||`${a.year}`));
}

export default async function Home() {
  const live=await getLiveOutputs();const all=live.length?live:outputs;
  const latest=all.slice(0,4);
  return <>
    <header className="siteHeader"><a className="wordmark" href="#home">MGL</a><nav aria-label="Primary navigation"><a href="#about">About</a><a href="#research">Research</a><a href="#publications">Publications</a><a href="#profile">Academic Profile</a></nav></header>
    <main>
      <section id="home" className="hero wrap"><p className="eyebrow">Researcher at Universidade Federal do Rio Grande do Sul</p><h1>Matheus Gallas Lopes, <span>PhD</span></h1><p className="fields">Meta-research · Translational validity · Evidence synthesis · Reproducibility</p></section>
      <section className="wrap latest" aria-labelledby="latest-title"><div className="sectionHead"><p className="kicker">Selected automatically</p><h2 id="latest-title">Latest research outputs</h2></div><div className="latestGrid">{latest.map((item,i)=><a className="latestItem" href={item.url} target="_blank" rel="noreferrer" key={item.title}><span className="index">0{i+1}</span><span className="outputType">{item.type} · {item.year}</span><h3>{item.title}</h3><span className="venue">{item.venue} ↗</span></a>)}</div></section>
      <section id="about" className="section wrap split"><div className="sectionHead"><p className="kicker">About</p><h2>Studying how research is designed, reported, synthesized, and translated.</h2></div><div className="prose"><p>I am a pharmacist and researcher at the Universidade Federal do Rio Grande do Sul, Brazil. My work examines the validity and reproducibility of preclinical research, with particular attention to the pathway from experimental findings to clinical application.</p><p>My research combines meta-research, systematic reviews, meta-analysis, replication studies, and open science practices. I also have a background in neuropharmacology and behavioral models using zebrafish and rodents.</p><p>I contribute to collaborative initiatives focused on research transparency, methodological robustness, evidence synthesis, and the improvement of biomedical research practices.</p></div></section>
      <section id="research" className="section researchBand"><div className="wrap"><div className="sectionHead"><p className="kicker">Research</p><h2>Research areas</h2></div><div className="researchList"><Research n="01" title="Meta-research and research integrity">Examining how study design, reporting practices, analytical choices, and research systems influence the reliability of scientific findings.</Research><Research n="02" title="Translational validity">Investigating the conditions associated with successful translation from preclinical experiments to clinical research and practice.</Research><Research n="03" title="Preclinical evidence synthesis">Using systematic reviews and advanced meta-analytic methods to evaluate evidence from animal and experimental research.</Research><Research n="04" title="Reproducibility and open science">Developing and evaluating practices that strengthen transparency, replicability, data sharing, and methodological robustness.</Research></div><div className="collab"><p className="kicker">Research & collaborations</p><h2>Collaborative science across disciplines and institutions.</h2><p>My work connects researchers in meta-science, pharmacology, neuroscience, evidence synthesis, and research integrity in Brazil and internationally.</p><div className="mapPlaceholder" role="img" aria-label="World map of research collaborations"><span>Collaboration map</span><small>Institution-level data generated from normalized OpenAlex affiliations.</small></div></div></div></section>
      <section id="publications" className="section wrap"><div className="sectionHead"><p className="kicker">Scholarly work</p><h2>Publications and research outputs</h2><p className="sectionIntro">Automatically updated records, classified by output type and deduplicated across scholarly sources.</p></div><Publications initial={all}/></section>
      <section id="profile" className="section wrap profile"><div className="sectionHead"><p className="kicker">Academic profile</p><h2>Positions, education, teaching, and service</h2></div><nav className="subnav" aria-label="Academic profile sections"><a href="#positions">Positions</a><a href="#education">Education</a><a href="#teaching">Teaching</a><a href="#honors">Honors</a><a href="#grants">Grants</a><a href="#service">Service</a></nav><ProfileSection id="positions" title="Positions & appointments" items={["2025–Present — Coordinating Team Member, Brazilian Reproducibility Initiative in preclinical Systematic review and meta-Analysis (BRISA)","2025–Present — Member, Brazilian Reproducibility Network","2023–2024 — Visiting Researcher, RCSI School of Medicine and Health Sciences, Ireland","2018–2022 — Member, Brazilian Reproducibility Initiative"]}/><ProfileSection id="education" title="Education" items={["2022–2026 — PhD in Biological Sciences: Pharmacology and Therapeutics, Universidade Federal do Rio Grande do Sul","2018–2022 — Bachelor of Pharmacy, Universidade Federal do Rio Grande do Sul"]}/><ProfileSection id="teaching" title="Teaching & mentorship" items={["Invited teaching in evidence synthesis, neuroendocrinology, and research integrity at RCSI and UFRGS","Graduate teaching in pharmacology and animal models for biomedical research","Training in preclinical systematic reviews and meta-analysis through BRISA","Undergraduate thesis co-supervision and research mentorship"]}/><ProfileSection id="honors" title="Honors & awards" items={["2025 — Einstein Foundation Award for Promoting Quality in Research (institutional award)","2025 — Scientific Exchange Grant, Swiss National Science Foundation","2025 — Travel Funding, Berlin Institute of Health at Charité","2024 — Early Career Award, Schizophrenia International Research Society","2024 — Travel Award, International Brain Research Organization","2023 — Outstanding Teaching Award, Universidade Federal do Rio Grande do Sul","2022 — Alfredo Leal Prize, First in Class, Pharmacy"]}/><ProfileSection id="grants" title="Grants" items={["Meta-Science Project Grant, Brazilian Reproducibility Network — Principal Investigator","CAPES/PRINT Short-Term International Training Grant","CAPES PhD Fellowship","CNPq/UFRGS Undergraduate Research Scholarship — six consecutive awards"]}/><ProfileSection id="service" title="Scientific service" items={["Member of multiple Task Forces, Brazilian Reproducibility Network","Communications Task Force Member, ILAE Young Epilepsy Section","Social Media Editor, Schizophrenia International Research Society","Ad hoc reviewer for international journals in neuroscience, pharmacology, toxicology, and research methods"]}/></section>
    </main>
    <footer><div className="wrap footerInner"><div><strong>Matheus Gallas Lopes</strong><a href="mailto:matheusgallasl@gmail.com">matheusgallasl@gmail.com</a></div><div className="footerLinks"><a href="https://orcid.org/0000-0001-5375-2335">ORCID</a><a href="https://scholar.google.com/citations?user=-bnP544AAAAJ">Google Scholar</a><a href="https://osf.io/5k9yv">OSF</a><a href="https://github.com/matheusglls">GitHub</a><a href="https://lattes.cnpq.br/4154743414245084">Lattes</a></div></div></footer>
  </>;
}
function Research({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <article><span>{n}</span><div><h3>{title}</h3><p>{children}</p></div></article>}
function ProfileSection({id,title,items}:{id:string,title:string,items:string[]}){return <section id={id} className="profileRow"><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section>}
